// <auto-generated />
using System;
using Desafio.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Desafio.API.Migrations
{
    [DbContext(typeof(DesafioDbContext))]
    [Migration("20210422060310_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Desafio.Models.Parcela", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdTitulo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdTitulo");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("Desafio.Models.Titulo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPFDevedor")
                        .HasColumnType("TEXT");

                    b.Property<float>("Juros")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<float>("Multa")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("NomeDevedor")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Titulos");
                });

            modelBuilder.Entity("Desafio.Models.Parcela", b =>
                {
                    b.HasOne("Desafio.Models.Titulo", "Titulo")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdTitulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("Desafio.Models.Titulo", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
